### ISSUE TITLE
[REQ] fix git license

### ISSUE THREAD

**Issue by MarcoRavich** [diewland/exo-player-rtsp-101#1]
In order to push the "IP video-streams' players" evolution, we're collecting/doxing related projects (yours too) in our [HyMPS project](https://github.com/forart/HyMPS) (under a [dedicated page](https://github.com/forart/HyMPS/blob/main/RTSP.md#--)), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly, as you can see:

![](https://flat.badgen.net/github/license/diewland/exo-player-rtsp-101)
(generator URL: https://flat.badgen.net/github/license/diewland/exo-player-rtsp-101)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse code in their projects which is a determining factor for the success and longevity of any open software.

Last but not least, we've recently opened a discussion about _[near-zero latency multiple (IP) video-streams playing](https://github.com/forart/HyMPS/discussions/17)_ to encourage a knowledge-exchange about this topic between developers/maintainers.

Hope that inspires !

**Comment by diewland** [comment]
MIT added. Thanks :)
